### ISSUE TITLE
Financials endpoint to v3

### ISSUE THREAD

**Issue by antoinevulcain** [patelneel55/financialmodelingprep#19]
Hello,

When doing:

fmp.stock('aapl').financial.income(period = 'annual').then(response => console.log(response));

I got :

```
{
  'Error Message': 'Invalid API KEY. Please retry or visit our documentation to create one FREE https://financialmodelingprep.com/developer/docs'
}
```

Also the endpoint are now:

`https://financialmodelingprep.com/api/v3/income-statement/{stock} `

instead of :

`https://financialmodelingprep.com/api/v3/financials/income-statement/{stock}
`

If you could look into this it would be awesome.

Thanks again, great package!

**Comment by KofiShango** [comment]
I'm also getting this. Is it just using the wrong api path?

**Comment by antoinevulcain** [comment]
@KofiShango yes it is. I think building from the api path is better at the moment
